# SwiftLint Configuration File
# See https://realm.github.io/SwiftLint/

opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - nimble_operator
  - private_action
  - redundant_nil_coalescing
  - sorted_first_last
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

excluded:
  - Carthage
  - Pods
  - fastlane
  - VibeKeeper.xcodeproj
  - VibeKeeper.xcworkspace

line_length: 120
