name: VibeKeeper CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test iOS
    runs-on: macos-14
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Swift Package Manager dependencies
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    # - name: Select Xcode version
    #   run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer

    - name: Build Application
      run: |
        xcodebuild build -scheme VibeKeeper \
                         -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
                         CODE_SIGN_IDENTITY="" \
                         CODE_SIGNING_REQUIRED=NO

    - name: Run Unit and UI Tests
      run: |
        xcodebuild test -scheme VibeKeeper \
                        -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
                        CODE_SIGN_IDENTITY="" \
                        CODE_SIGNING_REQUIRED=NO
